"use strict";
var message = "Hey Abu Hurairah,I have started learning TYPESCRIPT.";
console.log(message);
var num1 = 1;
var num2 = 2;
var num3 = 3;
var num4 = 4;
var num5 = 5;
var num6 = 6;
var num7 = 7;
var num8 = 8;
var num9 = 9;
var num10 = 10;
var addition = num1 + num2 + num3 + num4 + num5 + num6 + num7 + num8 + num9 + num10;
var subtraction = num1 - num2 - num3 - num4 - num5 - num6 - num7 - num8 - num9 - num10;
var multiplication = num1 * num2 * num3 * num4 * num5 * num6 * num7 * num8 * num9 * num10;
var division = num5 / num9;
console.log("Addition of numbers is", addition);
console.log("subtraction of numbers is", subtraction);
console.log("Multiplication of numbers is", multiplication);
console.log("Division of numbers is", division);
